version: '3.8'

networks:
  server-connection:
    external: true
    name: playsy_server-connection

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      # .env에서 NGINX_ENV_CONF 를 읽어와 dev or prd conf 를 결정한다.
      - ./nginx/nginx${NGINX_ENV_CONF}.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - server-connection
    environment:
      TZ: Asia/Seoul
    # depends_on:
    #   - front
    #   - back