version: '3.8'

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - server-connection
    depends_on:
      - front
      - back

  front:
    build: ./front
    networks:
      - server-connection
    ports:
      - 8080
    environment:
      SERVER_PORT: 8080
    scale: 2
  
  back:
    build: ./back
    networks:
      - server-connection
    ports:
      - 7080
    environment:
      DATABASE_URL: ${BACK_DATABASE_URL}
      SERVER_PORT: 7080
    volumes:
      - ./logs/back:/app/logs
    scale: 2