version: '3.8'
name: pb
networks:
  server-connection:
    external: true
    name: playsy_server-connection

services:
  front-blue:
    build: ./front
    networks:
      - server-connection
    ports:
      - 8080
    environment:
      SERVER_PORT: 8080
      TZ: Asia/Seoul
      PROFILE: ${PROFILE:-DEV}
    scale: 2
  
  back-blue:
    build: ./back
    networks:
      - server-connection
    ports:
      - 7080
    environment:
      DATABASE_URL: ${BACK_DATABASE_URL}
      SERVER_PORT: 7080
      TZ: Asia/Seoul
      PROFILE: ${PROFILE:-DEV}
      SWAGGER_USER: ${SWAGGER_USER}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
    volumes:
      - ./logs/back-blue:/app/logs
    scale: 2